name: tirmite
channels:
  - conda-forge
  - bioconda
dependencies:
  - "pymummer>=0.10.3"
  - blast
  - hmmer
  - mafft
  - pip
  - pyhmmer
  - python 3.12
  - pip:
      - "biopython>=1.70"
      - "pandas>=0.20.3"
      - rich
