name: tirmite
channels:
  - conda-forge
  - bioconda
dependencies:
  - aliview
  - blast
  - hmmer
  - mafft
  - pip
  - pyhmmer
  - python 3.12
  - samtools
  - seqkit
  - pip:
      - "biopython>=1.70"
      - "pandas>=0.20.3"
      - rich
