name: tirmitedev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::python=3.10
  - conda-forge::biopython  
  - pandas
  - tqdm
  - bioconda::pymummer>=0.10.3
  - bioconda::pyfaidx
  - bioconda::samtools
  - bioconda::pysam
  - bioconda::blast
  - bioconda::hmmer2
  - jupyter
 #- pip:
 #  - packagefrompip