# Publish main to pypi on new release
# https://dev.to/iamtekson/publish-package-to-pypi-and-release-new-version-using-github-actions-108k
# https://www.seanh.cc/2022/05/21/publishing-python-packages-from-github-actions/
# https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
# https://github.com/marketplace/actions/pypi-publish

# Publish container image to ghcr on new release

# Be sure to exclude dev files and dirs